import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { FolderPlus, Loader2, Tags, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function CategoriesPage() {
  const { user } = useAuth();
  const categories = trpc.catalog.categories.useQuery();
  const utils = trpc.useUtils();
  const [name, setName] = useState("");
  const create = trpc.catalog.createCategory.useMutation({ onSuccess: () => { toast.success("Categoria disponível no catálogo e nos pedidos."); setName(""); utils.catalog.categories.invalidate(); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin") return <div className="mx-auto max-w-3xl enter-up"><p className="section-kicker">Acesso restrito</p><h1 className="page-title mt-2">Categorias</h1><p className="mt-3 text-sm text-[#65656d]">Somente administradores podem alterar o catálogo operacional.</p></div>;
  return <div className="mx-auto max-w-4xl enter-up"><p className="section-kicker">Organização operacional</p><h1 className="page-title mt-2">Categorias</h1><p className="mt-2 text-sm text-[#65656d]">Categorias agrupam itens na lista de separação sem engessar as combinações de cada pedido.</p><div className="mt-8 grid gap-6 md:grid-cols-[1fr_330px]"><section className="surface-card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e5e5e8] p-5"><Tags className="text-[#e31937]" size={19} /><h2 className="font-display text-2xl font-bold uppercase">Categorias cadastradas</h2></div>{categories.isLoading ? <div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-[#e31937]" /></div> : categories.error ? <div className="grid min-h-52 place-items-center p-6 text-center"><TriangleAlert className="text-[#e31937]" /><p className="mt-3 text-sm text-[#65656d]">{categories.error.message}</p></div> : categories.data?.length === 0 ? <div className="grid min-h-52 place-items-center p-6 text-center"><Tags className="text-[#cfcfd4]" size={31} /><p className="mt-3 text-sm text-[#77777f]">Cadastre a primeira categoria para usar no catálogo.</p></div> : <div className="flex flex-wrap gap-2 p-5">{categories.data?.map(category => <span className="border border-[#dedee2] bg-[#fafafa] px-3 py-2 text-sm font-bold text-[#3f3f45]" key={category.id}>{category.name}</span>)}</div>}</section><section className="bg-[#171719] p-6 text-white"><FolderPlus className="text-[#e31937]" size={23} /><h2 className="font-display mt-4 text-3xl font-bold uppercase leading-none">Nova categoria</h2><p className="mt-3 text-xs leading-5 text-zinc-400">Crie agrupamentos que façam sentido para a equipe de separação.</p><form onSubmit={event => { event.preventDefault(); create.mutate({ name }); }} className="mt-6"><label className="text-xs font-extrabold uppercase tracking-[.08em] text-zinc-400">Nome<input value={name} onChange={event => setName(event.target.value)} required minLength={2} className="mt-2 h-11 w-full border border-white/20 bg-white px-3 text-sm font-bold text-[#242429] outline-none focus:border-[#e31937]" placeholder="Ex.: Alimentação" /></label><button disabled={create.isPending} className="inject-button mt-4 flex min-h-11 w-full items-center justify-center gap-2 px-4 text-sm">{create.isPending && <Loader2 className="animate-spin" size={16} />}Criar categoria</button></form><Link href="/products" className="mt-5 inline-block text-xs font-extrabold uppercase tracking-wide text-[#e31937]">Voltar para produtos</Link></section></div></div>;
}
