import { useAuth } from "@/_core/hooks/useAuth";
import { BrandMark } from "@/components/BrandMark";
import { startLogin } from "@/const";
import { ArrowRight, CheckCircle2, ClipboardCheck, Camera, PackageCheck } from "lucide-react";
import { Link } from "wouter";

const flow = [
  { icon: PackageCheck, title: "Pedido", text: "Cadastre o pedido e seus itens reais." },
  { icon: ClipboardCheck, title: "Conferência", text: "Separe, registre quantidades e divergências." },
  { icon: Camera, title: "Evidência", text: "Fotografe e finalize a operação com rastreabilidade." },
];

export default function Home() {
  const { user, loading } = useAuth();
  const enter = () => user ? window.location.assign("/app") : startLogin();
  return <div className="min-h-screen bg-[#09090a] text-white">
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><BrandMark /><button onClick={enter} disabled={loading} className="inject-outline-button min-h-10 border-white/25 bg-transparent px-4 text-sm text-white hover:bg-white/10">{user ? "Abrir operação" : "Entrar"}</button></header>
    <main>
      <section className="brand-slash relative overflow-hidden"><div className="relative z-10 mx-auto grid min-h-[630px] max-w-7xl items-center gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:py-20"><div className="enter-up"><p className="section-kicker">Sistema de produção</p><h1 className="font-display mt-5 max-w-3xl text-5xl font-bold uppercase leading-[.94] tracking-[-.035em] sm:text-6xl lg:text-7xl">Separação precisa.<br /><span className="border-b-4 border-[#e31937] pb-1 text-white">Operação no controle.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">Transforme cada pedido fechado em uma lista operacional clara para separar, conferir, fotografar e finalizar com segurança.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={enter} className="inject-button flex min-h-13 items-center justify-center gap-2 px-6 text-sm">Começar agora <ArrowRight size={18} /></button><a href="#como-funciona" className="inject-outline-button flex min-h-13 items-center justify-center px-6 text-sm text-white hover:bg-white/10">Conhecer o fluxo</a></div><div className="mt-10 grid max-w-lg grid-cols-1 gap-3 sm:grid-cols-3">{["Sem preços na operação", "Checklist por item", "Evidência em foto"].map(item => <div key={item} className="flex items-center gap-2 text-xs font-bold text-zinc-300"><CheckCircle2 size={16} className="shrink-0 text-[#e31937]" />{item}</div>)}</div></div><div className="relative mx-auto w-full max-w-md lg:max-w-none"><div className="absolute -inset-4 border border-[#e31937]/30" style={{ clipPath: "polygon(12% 0, 100% 0, 88% 100%, 0 100%)" }} /><div className="relative overflow-hidden bg-[#151518] p-4 sm:p-7"><div className="mb-5 flex items-center justify-between border-b border-white/10 pb-4"><span className="font-display text-xl uppercase">Lista de separação</span><span className="rounded-full bg-[#e31937] px-3 py-1 text-[.62rem] font-extrabold uppercase tracking-wider">Em operação</span></div><img src="/manus-storage/injectsolution-quadrijet_5228ddb0.webp" alt="Conjunto Quadrijet da InjectSolution" className="mx-auto h-60 w-full object-contain opacity-90 sm:h-72" /><div className="mt-3 grid grid-cols-2 gap-3"><div className="border-l-2 border-[#e31937] bg-white/5 p-3"><p className="text-[.62rem] font-bold uppercase tracking-wider text-zinc-500">Pedido</p><p className="font-display mt-1 text-2xl uppercase">#100001</p></div><div className="bg-white/5 p-3"><p className="text-[.62rem] font-bold uppercase tracking-wider text-zinc-500">Progresso</p><p className="font-display mt-1 text-2xl uppercase">12 <span className="text-sm text-zinc-500">/ 18</span></p></div></div></div></div></div></section>
      <section id="como-funciona" className="bg-[#f7f7f8] px-5 py-18 text-[#171719] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-kicker">Fluxo operacional</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="font-display max-w-xl text-4xl font-bold uppercase leading-none sm:text-5xl">Do pedido pronto<br />para a separação.</h2><p className="max-w-sm text-sm leading-6 text-[#65656d]">Uma sequência objetiva para a equipe executar sem depender da área comercial.</p></div><div className="mt-10 grid gap-px bg-[#dddde1] md:grid-cols-3">{flow.map(({ icon: Icon, title, text }, index) => <article key={title} className="bg-[#f7f7f8] p-7"><span className="font-display text-5xl text-[#e31937]">0{index + 1}</span><Icon className="mt-10 text-[#202024]" size={25} /><h3 className="font-display mt-4 text-2xl font-bold uppercase">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#65656d]">{text}</p></article>)}</div></div></section>
      <section className="px-5 py-18 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 border border-white/10 bg-[#171719] p-7 sm:p-10 lg:flex-row lg:items-center lg:justify-between"><div><p className="section-kicker">Pronto para operar</p><h2 className="font-display mt-3 text-4xl font-bold uppercase leading-none">Sua próxima separação<br />começa aqui.</h2></div><button onClick={enter} className="inject-button flex min-h-13 items-center justify-center gap-2 px-6 text-sm">Acessar sistema <ArrowRight size={18} /></button></div></section>
    </main>
    <footer className="border-t border-white/10 px-5 py-7 text-center text-xs text-zinc-600">InjectSolution — Sistema de Produção</footer>
  </div>;
}
