import { canEditOrder } from "@shared/operation";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Loader2, PackagePlus, Plus, Save, Trash2, TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation, useRoute } from "wouter";

type Unit = "UN" | "METRO" | "JOGO" | "PAR" | "KIT" | "CONJUNTO" | "OUTRO";
type LocalItem = { key: string; productId?: number; sku?: string; description: string; categoryName: string; quantity: number; unit: Unit; note: string };
type OrderForm = { blingOrderNumber: string; customerName: string; customerPhone: string; customerNote: string; vehicleBrand: string; vehicleModel: string; vehicleYear: string; vehicleEngine: string; vehicleCylinders: string; vehicleConfiguration: string; vehicleNotes: string; items: LocalItem[] };
const units: Unit[] = ["UN", "METRO", "JOGO", "PAR", "KIT", "CONJUNTO", "OUTRO"];
const blankItem = (): LocalItem => ({ key: crypto.randomUUID(), description: "", categoryName: "Outros", quantity: 1, unit: "UN", note: "" });
const blankOrder = (): OrderForm => ({ blingOrderNumber: "", customerName: "", customerPhone: "", customerNote: "", vehicleBrand: "", vehicleModel: "", vehicleYear: "", vehicleEngine: "", vehicleCylinders: "", vehicleConfiguration: "", vehicleNotes: "", items: [blankItem()] });

export default function OrderFormPage() {
  const { user } = useAuth();
  const [isEdit, params] = useRoute("/orders/:id/edit");
  const orderId = isEdit ? Number(params?.id) : undefined;
  const detail = trpc.orders.get.useQuery({ id: orderId ?? 1 }, { enabled: Boolean(orderId) });
  const catalog = trpc.catalog.products.useQuery();
  const categories = trpc.catalog.categories.useQuery();
  const utils = trpc.useUtils();
  const [, setLocation] = useLocation();
  const [form, setForm] = useState<OrderForm>(blankOrder);
  const [loadedOrder, setLoadedOrder] = useState<number | null>(null);
  const categoryNames = useMemo(() => Array.from(new Set([...(categories.data?.map(category => category.name) ?? []), "Alimentação", "Combustível", "Gerenciamento Eletrônico", "Chicote", "Sensores", "Ignição", "Admissão", "Complementos", "Opcionais", "Outros"])), [categories.data]);

  useEffect(() => { if (detail.data && orderId && loadedOrder !== orderId) { const { order, items } = detail.data; setForm({ blingOrderNumber: order.blingOrderNumber, customerName: order.customerName, customerPhone: order.customerPhone || "", customerNote: order.customerNote || "", vehicleBrand: order.vehicleBrand || "", vehicleModel: order.vehicleModel || "", vehicleYear: order.vehicleYear ? String(order.vehicleYear) : "", vehicleEngine: order.vehicleEngine || "", vehicleCylinders: order.vehicleCylinders || "", vehicleConfiguration: order.vehicleConfiguration || "", vehicleNotes: order.vehicleNotes || "", items: items.map(item => ({ key: crypto.randomUUID(), productId: item.productId ?? undefined, sku: item.sku ?? undefined, description: item.description, categoryName: item.categoryName, quantity: item.quantity, unit: item.unit, note: item.note || "" })) }); setLoadedOrder(orderId); } }, [detail.data, orderId, loadedOrder]);
  const mutationOptions = { onSuccess: (result: { id: number }) => { toast.success(isEdit ? "Pedido atualizado com sucesso." : "Pedido criado. A lista de separação está pronta."); utils.orders.list.invalidate(); utils.dashboard.overview.invalidate(); setLocation(`/orders/${result.id}`); }, onError: (error: { message: string }) => toast.error(error.message) };
  const create = trpc.orders.create.useMutation(mutationOptions);
  const update = trpc.orders.update.useMutation(mutationOptions);
  const pending = create.isPending || update.isPending;
  if (user?.role !== "admin") return <div className="mx-auto max-w-3xl enter-up"><p className="section-kicker">Acesso restrito</p><h1 className="page-title mt-2">Cadastro de pedidos</h1><p className="mt-3 text-sm text-[#65656d]">O perfil separador executa a conferência dos pedidos existentes, mas não cria nem edita pedidos.</p><Link href="/orders" className="inject-button mt-6 inline-flex min-h-11 items-center px-5 text-sm">Voltar para pedidos</Link></div>;
  const setField = <K extends Exclude<keyof OrderForm, "items">>(field: K, value: OrderForm[K]) => setForm(current => ({ ...current, [field]: value }));
  const editItem = (key: string, patch: Partial<LocalItem>) => setForm(current => ({ ...current, items: current.items.map(item => item.key === key ? { ...item, ...patch } : item) }));
  const useProduct = (productId: number) => { const product = catalog.data?.find(item => item.id === productId); if (!product) return; const productCategory = categories.data?.find(category => category.id === product.categoryId)?.name ?? "Outros"; setForm(current => ({ ...current, items: [...current.items, { key: crypto.randomUUID(), productId: product.id, sku: product.sku || undefined, description: product.name, categoryName: productCategory, quantity: 1, unit: product.unit, note: product.note || "" }] })); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (pending) return; const payload = { ...form, vehicleYear: form.vehicleYear ? Number(form.vehicleYear) : undefined, items: form.items.map(({ key, ...item }) => item) }; if (isEdit && orderId) update.mutate({ id: orderId, ...payload }); else create.mutate(payload); };
  if (isEdit && detail.isLoading) return <div className="grid min-h-[55vh] place-items-center"><Loader2 className="animate-spin text-[#e31937]" /></div>;
  if (isEdit && detail.error) return <div className="surface-card p-7"><TriangleAlert className="text-[#e31937]" /><p className="mt-3 text-sm">{detail.error.message}</p></div>;
  return <div className="mx-auto max-w-7xl pb-32"><Link href={isEdit && orderId ? `/orders/${orderId}` : "/orders"} className="inline-flex items-center gap-2 text-sm font-extrabold text-[#65656d] transition-colors hover:text-[#e31937]"><ArrowLeft size={16} />Voltar para pedidos</Link><div className="mt-6"><p className="section-kicker">{isEdit ? "Editar pedido" : "Novo pedido"}</p><h1 className="page-title mt-2">{isEdit ? "Atualizar ordem" : "Criar ordem de separação"}</h1><p className="mt-2 text-sm text-[#65656d]">Cadastre apenas dados operacionais. Valores e informações financeiras não fazem parte deste fluxo.</p></div>
    <form id="order-form" onSubmit={submit} className="mt-8 grid gap-6 xl:grid-cols-[1fr_340px]"><div className="space-y-6"><section className="surface-card p-5 sm:p-7"><h2 className="font-display text-2xl font-bold uppercase">Identificação e cliente</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Número do pedido Bling" required><input value={form.blingOrderNumber} onChange={event => setField("blingOrderNumber", event.target.value)} required className="field" placeholder="Ex.: 100001" /></Field><Field label="Cliente" required><input value={form.customerName} onChange={event => setField("customerName", event.target.value)} required className="field" placeholder="Nome completo" /></Field><Field label="Telefone"><input value={form.customerPhone} onChange={event => setField("customerPhone", event.target.value)} className="field" placeholder="(00) 00000-0000" /></Field><Field label="Observação do cliente"><input value={form.customerNote} onChange={event => setField("customerNote", event.target.value)} className="field" placeholder="Informação relevante" /></Field></div></section>
      <section className="surface-card p-5 sm:p-7"><h2 className="font-display text-2xl font-bold uppercase">Veículo e configuração</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Marca"><input value={form.vehicleBrand} onChange={event => setField("vehicleBrand", event.target.value)} className="field" placeholder="Chevrolet" /></Field><Field label="Modelo"><input value={form.vehicleModel} onChange={event => setField("vehicleModel", event.target.value)} className="field" placeholder="Opala" /></Field><Field label="Ano"><input value={form.vehicleYear} onChange={event => setField("vehicleYear", event.target.value)} className="field" inputMode="numeric" placeholder="1974" /></Field><Field label="Motor"><input value={form.vehicleEngine} onChange={event => setField("vehicleEngine", event.target.value)} className="field" placeholder="261" /></Field><Field label="Cilindros"><input value={form.vehicleCylinders} onChange={event => setField("vehicleCylinders", event.target.value)} className="field" placeholder="4 cilindros" /></Field><Field label="Configuração"><input value={form.vehicleConfiguration} onChange={event => setField("vehicleConfiguration", event.target.value)} className="field" placeholder="TBI 42 mm + FT300" /></Field><div className="sm:col-span-2 lg:col-span-3"><Field label="Observações do veículo"><textarea value={form.vehicleNotes} onChange={event => setField("vehicleNotes", event.target.value)} className="field min-h-22 resize-y" placeholder="Detalhes técnicos, adaptação ou instruções de montagem" /></Field></div></div></section>
      <section className="surface-card overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#e6e6e8] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-2xl font-bold uppercase">Itens da separação</h2><p className="mt-1 text-xs text-[#77777f]">Adicione cada produto individualmente. O catálogo é apenas uma ajuda de busca.</p></div><button type="button" onClick={() => setForm(current => ({ ...current, items: [...current.items, blankItem()] }))} className="inject-outline-button flex min-h-10 items-center justify-center gap-2 px-4 text-sm"><Plus size={16} />Adicionar item</button></div><div className="divide-y divide-[#ececef]">{form.items.map((item, index) => <div key={item.key} className="p-5"><div className="mb-4 flex items-center justify-between"><p className="font-display text-lg font-bold uppercase text-[#343439]">Item {String(index + 1).padStart(2, "0")}</p><button type="button" disabled={form.items.length === 1} onClick={() => setForm(current => ({ ...current, items: current.items.filter(candidate => candidate.key !== item.key) }))} className="text-xs font-extrabold uppercase tracking-wide text-[#77777f] hover:text-[#e31937] disabled:cursor-not-allowed disabled:opacity-40"><Trash2 className="mr-1 inline" size={14} />Remover</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-[86px_1fr_170px_132px]"><Field label="Qtd." required><input type="number" min="1" value={item.quantity} onChange={event => editItem(item.key, { quantity: Math.max(1, Number(event.target.value)) })} required className="field" /></Field><Field label="Produto" required><input value={item.description} onChange={event => editItem(item.key, { description: event.target.value })} required className="field" placeholder="Descrição do produto" /></Field><Field label="Categoria" required><input list="categories" value={item.categoryName} onChange={event => editItem(item.key, { categoryName: event.target.value })} required className="field" placeholder="Categoria" /><datalist id="categories">{categoryNames.map(name => <option key={name} value={name} />)}</datalist></Field><Field label="Unidade"><select value={item.unit} onChange={event => editItem(item.key, { unit: event.target.value as Unit })} className="field">{units.map(unit => <option key={unit}>{unit}</option>)}</select></Field><div className="sm:col-span-2 lg:col-span-4"><Field label="Observação"><input value={item.note} onChange={event => editItem(item.key, { note: event.target.value })} className="field" placeholder="Instrução operacional, especificação ou detalhe" /></Field></div></div></div>)}</div></section></div>
      <aside className="space-y-5 xl:sticky xl:top-22 xl:self-start"><section className="bg-[#171719] p-6 text-white"><p className="section-kicker">Resumo da ordem</p><p className="font-display mt-3 text-5xl font-bold leading-none">{form.items.length}</p><p className="mt-1 text-xs font-bold uppercase tracking-[.1em] text-zinc-500">Itens cadastrados</p><div className="mt-7 border-t border-white/10 pt-5"><p className="text-xs leading-5 text-zinc-400">Ao salvar, a ordem fica pronta para a lista de separação e conferência.</p><p className="mt-5 text-xs text-zinc-400">Use o botão Salvar pedido na barra inferior, disponível durante todo o cadastro.</p></div></section><section className="surface-card p-5"><div className="flex items-center gap-2"><PackagePlus className="text-[#e31937]" size={18} /><h2 className="font-display text-lg font-bold uppercase">Catálogo rápido</h2></div><p className="mt-2 text-xs leading-5 text-[#77777f]">Use os produtos previamente cadastrados para preencher itens mais rápido.</p><div className="mt-4 max-h-64 space-y-2 overflow-y-auto">{catalog.isLoading && <Loader2 size={17} className="animate-spin text-[#e31937]" />}{catalog.data?.map(product => <button type="button" onClick={() => useProduct(product.id)} key={product.id} className="w-full border border-[#e4e4e7] p-3 text-left transition-colors hover:border-[#e31937] hover:bg-[#fff8f8]"><p className="text-xs font-extrabold text-[#303035]">{product.name}</p><p className="mt-1 text-[.65rem] uppercase tracking-wide text-[#77777f]">{product.sku || "Sem SKU"} · {product.unit}</p></button>)}{!catalog.isLoading && catalog.data?.length === 0 && <p className="text-xs text-[#77777f]">Cadastre produtos no catálogo para usá-los como atalho.</p>}</div><Link href="/products" className="mt-4 inline-block text-xs font-extrabold uppercase tracking-wide text-[#e31937]">Gerenciar catálogo</Link></section></aside></form><div className="no-print fixed inset-x-0 bottom-0 z-40 border-t border-[#dedee2] bg-white px-4 pt-3 shadow-[0_-4px_20px_rgba(0,0,0,.08)] lg:left-[272px]" style={{ paddingBottom: "max(12px, env(safe-area-inset-bottom))" }}><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><div><p className="text-sm font-extrabold">{form.items.length} produto(s) no pedido</p><p className="text-xs text-[#65656d]">{pending ? "Salvando…" : "Revise os produtos e salve quando concluir."}</p></div><button type="submit" form="order-form" disabled={pending} className="inject-button flex min-h-12 shrink-0 items-center justify-center gap-2 px-5 text-sm">{pending ? <Loader2 className="animate-spin" size={17} /> : <Save size={17} />}{pending ? "Salvando…" : isEdit ? "Salvar alterações" : "Salvar pedido"}</button></div></div></div>;
}

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className="block text-xs font-extrabold uppercase tracking-[.065em] text-[#4a4a50]">{label}{required && <span className="ml-1 text-[#e31937]">*</span>}<span className="mt-2 block">{children}</span></label>; }
