import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { measurementTemplates, measureLabels, type MeasurementConfig } from "@shared/measurements";
import MeasurementPrint from "@/components/MeasurementPrint";
export default function OrderMeasurementsPage(){
  const {user}=useAuth(); const [,params]=useRoute('/orders/:id/measurements');const orderId=Number(params?.id);
  const detail=trpc.orders.get.useQuery({id:orderId},{enabled:user?.role==='admin'});
  const sheet=trpc.measurements.get.useQuery({orderId},{enabled:user?.role==='admin'});
  const [template,setTemplate]=useState<keyof typeof measurementTemplates>('jeep');
  const [config,setConfig]=useState<MeasurementConfig>({model:measurementTemplates.jeep.name,module:'',standards:measurementTemplates.jeep.values,instructions:''});
  const [loaded,setLoaded]=useState(false);const [links,setLinks]=useState<{customer:string;supplier:string}|null>(null);
  useEffect(()=>{if(sheet.data && !loaded){setConfig(sheet.data.config);setLoaded(true);}},[sheet.data,loaded]);
  const issue=trpc.measurements.issue.useMutation({onSuccess:data=>{setLinks({customer:`${location.origin}/medidas#${data.customerToken}`,supplier:`${location.origin}/medidas#${data.supplierToken}`});sheet.refetch();toast.success('Links gerados. Validade de 7 dias.');},onError:e=>toast.error(e.message)});
  const revoke=trpc.measurements.revoke.useMutation({onSuccess:()=>{setLinks(null);sheet.refetch();toast.success('Links cancelados. A ficha foi preservada.');},onError:e=>toast.error(e.message)});
  if(user?.role!=='admin')return <p>Apenas administradores podem gerenciar as fichas de medidas.</p>;
  if(detail.isLoading || sheet.isLoading)return <p>Carregando ficha…</p>;
  if(detail.error || sheet.error || !detail.data)return <p role="alert">{detail.error?.message || sheet.error?.message || 'Pedido indisponível.'}</p>;
  const order=detail.data.order;const busy=issue.isPending||revoke.isPending;
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);toast.success('Link copiado.');}catch{toast.error('Selecione e copie o link no campo.');}};
  return <div className="mx-auto max-w-5xl space-y-6"><Link href={`/orders/${orderId}`} className="text-sm font-bold">← Voltar ao pedido</Link><header><p className="section-kicker mt-4">Pedido #{order.blingOrderNumber}</p><h1 className="page-title mt-2">Medidas do chicote</h1><p className="mt-3 text-sm">Revise as medidas de referência antes de enviar. O cliente confirma ou personaliza cada trecho; o fornecedor recebe um link somente de consulta.</p></header>
    <section className="surface-card p-5"><h2 className="font-display text-2xl font-bold">ACESSO SEM LOGIN · 7 DIAS</h2><p className="mt-2 text-sm">Quem receber o link poderá acessar a ficha durante sua validade. Compartilhe cada link apenas com o destinatário correspondente. Os logs ficam exclusivos dos admins.</p>{sheet.data && <><p className="mt-3 text-sm">{sheet.data.expiresAt && new Date(sheet.data.expiresAt)>new Date()?`Válidos até ${new Date(sheet.data.expiresAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} (Brasília)`:'Links expirados ou cancelados.'}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} className="inject-outline-button min-h-11 px-4" onClick={()=>{if(confirm('Gerar novos links por 7 dias? Os links anteriores deixarão de funcionar. As respostas serão preservadas.'))issue.mutate({orderId});}}>Renovar links por 7 dias</button><button disabled={busy} className="inject-outline-button min-h-11 px-4" onClick={()=>revoke.mutate({orderId})}>Cancelar links</button><button className="inject-outline-button min-h-11 px-4" onClick={()=>window.print()}>Imprimir / Salvar PDF</button></div></>}{links && <div className="mt-5 grid gap-4">{([['customer','Cliente · preencher'],['supplier','Fornecedor · consultar']] as const).map(([key,label])=><label className="block text-sm font-bold" key={key}>{label}<div className="mt-2 flex gap-2"><input readOnly className="field" value={links[key]} onFocus={e=>e.target.select()}/><button type="button" onClick={()=>copy(links[key])} className="inject-outline-button px-4">Copiar</button></div></label>)}<p className="text-xs">Copie os links agora. Ao sair desta página, gere novos links para compartilhar novamente.</p></div>}</section>
    {sheet.data?.response && <section className="surface-card p-5"><h2 className="font-display text-2xl font-bold">CONFERÊNCIA RECEBIDA</h2><p className="mt-2 text-sm">Nome informado: {sheet.data.response.responsible} · {sheet.data.submittedAt && new Date(sheet.data.submittedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p><div className="mt-4 divide-y">{sheet.data.response.answers.map((a,i)=><p key={i} className="py-2 text-sm"><strong>{measureLabels[i]}</strong>: padrão {sheet.data!.config.standards[i] ?? 'não se aplica'} → {a.cm===null?'não se aplica':`${a.cm} cm`} · {{confirm:'Confirmado',change:'Personalizado',na:'Não se aplica'}[a.choice]}</p>)}</div><p className="mt-4 whitespace-pre-wrap text-sm">Observações: {sheet.data.response.notes || 'Nenhuma informada'}</p></section>}
    <form className="surface-card space-y-5 p-5" onSubmit={e=>{e.preventDefault();if(sheet.data&&!confirm('Substituir a ficha? As respostas atuais serão removidas desta ficha e os links anteriores serão cancelados. O histórico de envios será preservado nos logs.'))return;issue.mutate({orderId,config});}}><h2 className="font-display text-2xl font-bold">{sheet.data?'REVISAR PADRÕES E SUBSTITUIR FICHA':'PREPARAR MEDIDAS PADRÃO'}</h2><p className="text-sm">Modelos extraídos dos exemplos enviados. Ajuste as referências para este veículo. Campo vazio significa não se aplica / sem padrão. A observação de +10 cm do Maverick não foi aplicada ao modelo.</p><label className="block text-sm font-bold">Carregar modelo<select className="field mt-2" value={template} onChange={e=>{const key=e.target.value as keyof typeof measurementTemplates;setTemplate(key);setConfig({...config,model:measurementTemplates[key].name,standards:[...measurementTemplates[key].values]});}}>{Object.entries(measurementTemplates).map(([key,t])=><option value={key} key={key}>{t.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Veículo / modelo<input required className="field mt-2" value={config.model} onChange={e=>setConfig({...config,model:e.target.value})}/></label><label className="text-sm font-bold">Módulo EFI<input className="field mt-2" value={config.module} onChange={e=>setConfig({...config,module:e.target.value})}/></label></div><div className="grid gap-4 sm:grid-cols-2">{measureLabels.map((label,i)=><label key={label} className="text-sm font-bold">{label} (cm)<input className="field mt-2" type="number" min="0.01" max="10000" step="any" value={config.standards[i]??''} placeholder="Não se aplica / sem padrão" onChange={e=>setConfig({...config,standards:config.standards.map((v,j)=>j===i?(e.target.value===''?null:Number(e.target.value)):v)})}/></label>)}</div><label className="block text-sm font-bold">Orientações para o cliente<textarea maxLength={3000} className="field mt-2 min-h-24" value={config.instructions} onChange={e=>setConfig({...config,instructions:e.target.value})}/></label><button disabled={busy} className="inject-button min-h-12 px-5">{busy?'Salvando…':sheet.data?'Substituir ficha e gerar novos links':'Salvar ficha e gerar links por 7 dias'}</button></form>
    {sheet.data && <MeasurementPrint config={sheet.data.config} response={sheet.data.response} number={order.blingOrderNumber} submittedAt={sheet.data.submittedAt}/>}
  </div>;
}
