import { useEffect, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { measureLabels, type MeasurementResponse } from "@shared/measurements";
import MeasurementPrint from "@/components/MeasurementPrint";
import type { inferRouterOutputs } from "@trpc/server";
import type { AppRouter } from "../../../server/routers";
type Sheet = inferRouterOutputs<AppRouter>["measurements"]["read"];
type DraftAnswer = { choice: "" | "confirm" | "change" | "na"; cm: number | null };
export default function PublicMeasurementsPage() {
  const [token] = useState(() => window.location.hash.slice(1));
  const [sheet, setSheet] = useState<Sheet | null>(null);
  const [answers,setAnswers]=useState<DraftAnswer[]>(measureLabels.map(()=>({choice:"",cm:null})));
  const [notes,setNotes]=useState(""); const [responsible,setResponsible]=useState(""); const [dirty,setDirty]=useState(false);
  const [now,setNow]=useState(Date.now());
  const read=trpc.measurements.read.useMutation({onSuccess:data=>{setSheet(data);setAnswers(data.response?.answers ?? measureLabels.map(()=>({choice:"",cm:null})));setNotes(data.response?.notes ?? "");setResponsible(data.response?.responsible ?? "");setDirty(false);}});
  const submit=trpc.measurements.submit.useMutation({onSuccess:()=>{toast.success("Medidas enviadas. A InjectSolution e o fornecedor poderão consultar a ficha.");read.mutate({token});},onError:e=>toast.error(e.message)});
  useEffect(()=>{if(/^[a-f0-9]{64}$/.test(token))read.mutate({token});},[token]);
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
  const expired=sheet?.expiresAt ? new Date(sheet.expiresAt).getTime()<=now : false;
  if(!/^[a-f0-9]{64}$/.test(token)||read.error||expired)return <main className="mx-auto max-w-2xl p-8"><h1 className="page-title">Link indisponível</h1><p className="mt-4">{read.error?.message || "Este link expirou ou não está completo. Solicite um novo link à InjectSolution."}</p></main>;
  if(!sheet)return <p className="p-8">Carregando ficha…</p>;
  const editable=sheet.mode==="customer";
  const update=(i:number,patch:Partial<DraftAnswer>)=>{setAnswers(current=>current.map((a,j)=>j===i?{...a,...patch}:a));setDirty(true);};
  const send=(e:React.FormEvent)=>{e.preventDefault();if(answers.some(a=>!a.choice)){toast.error("Confira todos os trechos antes de enviar.");return;}submit.mutate({token,revision:sheet.revision,response:{answers:answers as MeasurementResponse["answers"],notes,responsible}});};
  return <main className="mx-auto max-w-4xl space-y-5 p-4 pb-28 sm:p-8 sm:pb-28">
    <header className="surface-card p-6"><p className="section-kicker">InjectSolution</p><h1 className="page-title mt-2">Medidas do chicote</h1><p className="mt-3 font-bold">Pedido #{sheet.orderNumber} · {sheet.config.model}</p><p className="mt-1 text-sm">{[sheet.vehicle,sheet.year,sheet.engine].filter(Boolean).join(" · ")}</p><p className="mt-1 text-sm">Módulo EFI: {sheet.config.module || "Não informado"}</p><p className="mt-3 text-sm">{editable ? "Confira cada medida em centímetros. Confirme o padrão ou informe a personalização desejada." : "Consulta do fornecedor. Confira as medidas solicitadas e as observações do cliente."}</p><p className="mt-3 text-xs">Link válido até {new Date(sheet.expiresAt!).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})} (Brasília).</p>{sheet.submittedAt && <p className="mt-2 text-sm font-bold">Último envio: {new Date(sheet.submittedAt).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})} (Brasília)</p>}{!sheet.response && <p className="mt-2 text-sm font-bold text-amber-800">Aguardando conferência do cliente.</p>}{sheet.config.instructions && <p className="mt-4 whitespace-pre-wrap text-sm">Orientações: {sheet.config.instructions}</p>}</header>
    <form id="measurement-form" onSubmit={send} className="space-y-4"><fieldset disabled={submit.isPending || read.isPending} className="space-y-4">{measureLabels.map((label,i)=><section key={label} className="surface-card p-5"><h2 className="font-bold">{i+1}. {label}</h2><p className="mt-2 text-sm">Medida padrão: <strong>{sheet.config.standards[i] === null ? "Não se aplica / sem medida padrão" : `${sheet.config.standards[i]} cm`}</strong></p>{editable ? <><div className="mt-4 flex flex-wrap gap-4">{([['confirm','✓ Confirmo o padrão'],['change','Quero alterar'],['na','Não se aplica']] as const).map(([value,text])=><label key={value} className="flex min-h-11 items-center gap-2 text-sm"><input type="radio" name={`measure-${i}`} checked={answers[i].choice===value} disabled={value==='confirm' && sheet.config.standards[i]===null} onChange={()=>update(i,{choice:value,cm:value==='confirm'?sheet.config.standards[i]:null})}/>{text}</label>)}</div>{answers[i].choice==='change' && <label className="mt-3 block text-sm font-bold">Medida desejada (cm)<input required type="number" min="0.01" max="10000" step="any" inputMode="decimal" className="field mt-2 max-w-xs" value={answers[i].cm ?? ''} onChange={e=>update(i,{cm:e.target.value===''?null:Number(e.target.value)})}/></label>}</> : <p className="mt-3 text-sm font-bold">{sheet.response ? `${{confirm:'Confirmado',change:'Personalizado',na:'Não se aplica'}[sheet.response.answers[i].choice]}${sheet.response.answers[i].cm!==null ? ` · ${sheet.response.answers[i].cm} cm` : ''}` : 'Pendente'}</p>}</section>)}
      <section className="surface-card p-5"><label className="block text-sm font-bold">Observações<textarea readOnly={!editable} className="field mt-2 min-h-32" maxLength={3000} value={notes} onChange={e=>{setNotes(e.target.value);setDirty(true);}} placeholder="Detalhes sobre a personalização, instalação ou trechos que não se aplicam"/></label><label className="mt-5 block text-sm font-bold">Responsável pelas medições (nome informado)<input readOnly={!editable} required maxLength={160} className="field mt-2" value={responsible} onChange={e=>{setResponsible(e.target.value);setDirty(true);}}/></label></section></fieldset></form>
    <div className="no-print fixed inset-x-0 bottom-0 z-40 border-t bg-white p-4 shadow-lg"><div className="mx-auto flex max-w-4xl flex-wrap items-center justify-between gap-3"><p className="text-xs">{dirty ? 'Alterações ainda não enviadas.' : 'A impressão usa a última ficha salva.'}</p><div className="flex flex-wrap gap-2"><button className="inject-outline-button min-h-11 px-4" disabled={dirty || read.isPending} onClick={()=>window.print()}>Imprimir / Salvar PDF</button>{editable ? <button form="measurement-form" className="inject-button min-h-11 px-4" disabled={submit.isPending || read.isPending}> {submit.isPending?'Enviando…':'Enviar conferência'}</button> : <button className="inject-outline-button min-h-11 px-4" disabled={read.isPending} onClick={()=>read.mutate({token})}>Atualizar ficha</button>}</div></div></div>
    <MeasurementPrint config={sheet.config} response={sheet.response} number={sheet.orderNumber} submittedAt={sheet.submittedAt}/>
  </main>;
}
